# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-gb
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
fr:
  languageCode: fr
  contentDir: content/fr
  title: un toucan qui parle
  params:
    description: Blog et portfolio de Kanto Fiaferana
  menu:
    main:
      - name: Ã€ propos
        url: 'a-propos/'
        weight: 1
      - name: Blog
        url: 'post/'
        weight: 20
      - name: Projets
        url: 'projets/'
        weight: 30
      - name: CV
        url: 'cv/'
        weight: 40
